headingLevels:
  - 2
  - 3
  - 4
  - 5
name: 'Long Content'
options:
  link:
    decorators:
      openInNewTab:
        attributes:
          rel: 'noopener noreferrer'
          target: _blank
        label: 'Open in a new tab'
        mode: manual
toolbar:
  - heading
  - createEntry
  - '|'
  - bold
  - italic
  - link
  - bulletedList
  - todoList
  - numberedList
  - '|'
  - blockQuote
  - insertTable
  - '|'
  - sourceEditing
