headingLevels: false
name: Simple
options:
  link:
    decorators:
      openInNewTab:
        attributes:
          rel: 'noopener noreferrer'
          target: _blank
        label: 'Open in a new tab'
        mode: manual
toolbar:
  - bold
  - italic
  - link
  - '|'
  - bulletedList
  - numberedList
