headingLevels:
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
name: 'Short Content'
toolbar:
  - heading
  - '|'
  - bold
  - italic
  - link
  - insertImage
  - bulletedList
  - todoList
  - numberedList
  - '|'
  - sourceEditing
