baseUrl: $PORTUGUESE_URL
enabled: '0'
handle: portuguese
hasUrls: true
language: pt
name: 'G O L D E N - Portuguese'
primary: false
siteGroup: 12103b78-4726-4c36-9ee1-687ea17c4c15 # Sites
sortOrder: 5
