altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  acaeea1e-cbd8-4d88-b343-4d6843673bfa:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-03-27T21:20:23+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: b39d9909-4777-4885-a4e4-464886201a2d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 08db827f-c1a7-475d-9a14-f6fe00dd5689
        userCondition: null
fs: $FILES_FS
handle: images
name: Images
sortOrder: 2
subpath: images
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
