fieldLayouts:
  5466dd62-b916-419e-9f2d-98063dc791a0:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: Title
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: bad0b809-0b3b-4dd6-aa60-cdacc2031aee
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 771ba179-2c59-4389-bad3-882ce829a509 # Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c90346e2-1ca5-44bd-837d-69ba0662317d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0ae9699f-02b3-4ff0-bd73-ea5c2c0476e4 # Subheading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 87b9635b-b0a8-420a-b41a-44b85bcb15d3
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6d8c2249-7976-4ec4-9ebe-db7e553e73fd # Show Date & Author
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 96504b63-5c30-4283-b5b6-96a8ea8089af
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: bcaf43d6-0a78-4d23-983d-b0c2cc60d59c # Thumbnail
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c94d516a-03f9-4825-812d-8160d770b47a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9afe3d99-95db-4f7d-977b-d12ff3c82fa9 # Body
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dc1e4682-533f-4e3f-9f92-8eaae9b5c652
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c7380c3d-c34b-4be1-bc87-601956014cce # Application Category
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8243d5ab-a30f-4626-b2d5-23fad6663a25
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 14b10afb-9c39-4ca4-a740-c4bbbd04f101 # Page Builder
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4ce3b338-6413-4047-8837-2fb59999f2e0
            userCondition: null
            warning: null
            width: 100
        name: Capabilities
        uid: 444981c7-742b-490f-9865-d019e7c5fed1
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 2d042d9b-af16-4d98-9347-8aadaad910b4 # Page Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7ac3a61e-c35e-4e94-a656-0a5b199562b4
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 784189f8-141b-4901-a137-08ab2d5b1a56 # Meta Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c95aadda-dc50-4b2b-ba0e-26354ed3bd2e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2de2c9bb-2614-4aee-92ad-8acc2273975d # Canonical URL
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1715f1e1-0729-4bcb-af51-44dcbcd719d9
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: dda2aa22-ce74-41a0-b919-85a4bc5563a7 # Robots Noindex, Nofollow
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 43aa7981-93d9-4932-b0e1-b865624b049a
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: eaa8bd8c-d913-41e0-9b34-be0a2cd60d29
        userCondition: null
handle: applications
hasTitleField: true
name: Applications
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: ''
