color: null
fieldLayouts:
  8fb266fc-57f7-4454-a243-b7bbbc9f0a24:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-03-27T22:25:45+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 028d84f4-25a0-4953-bc9e-24801e457c78
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-03-27T22:27:07+00:00'
            elementCondition: null
            fieldUid: 6d911a2a-162d-4f6f-ade3-7e274512eb58 # Hero
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7c958fb2-fd9a-456a-b2bf-564b6dc1a2eb
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: a772b1c0-1ab6-4110-8478-5975a1434f0c
        userCondition: null
handle: blogIndex
hasTitleField: true
icon: file
name: 'Blog Index'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
