color: null
fieldLayouts:
  1bcb2d33-d2ea-41b1-a442-c5e6a87454c0:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-02-26T12:47:10+00:00'
            elementCondition: null
            fieldUid: ea95c7de-c507-4012-a3c8-afe1ed993baf
            handle: null
            includeInCards: true
            instructions: null
            label: 'Booth Brand'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ffa3c24c-5fe4-427b-a197-01e1926851d9
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-26T12:47:10+00:00'
            elementCondition: null
            fieldUid: daae0358-2016-4ae5-a726-f8a6249c6f06
            handle: null
            includeInCards: false
            instructions: null
            label: 'Booth #'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7ae69c68-5ea9-43d9-af19-5f4232868b47
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-26T12:47:10+00:00'
            elementCondition: null
            fieldUid: e3b86ef5-8629-4abd-bca1-d4bd056db712
            handle: null
            includeInCards: false
            instructions: null
            label: Description
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 77172add-1183-4ade-8a6f-b48257c24a05
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-26T12:47:10+00:00'
            elementCondition: null
            fieldUid: dbbb84ac-14fe-495d-9763-3a7469c406f6
            handle: null
            includeInCards: false
            instructions: null
            label: Offer
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4a3ce3a8-e38f-43f1-bdae-57dc77e467a6
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 0ff9ea16-1c29-4095-8415-a8e1e54b3c26
        userCondition: null
handle: brandBooth
hasTitleField: false
icon: null
name: 'Brand Booth'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
