color: null
fieldLayouts:
  2f8f53a1-e554-47d9-998d-494db3580e35:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-02-26T12:47:10+00:00'
            elementCondition: null
            fieldUid: 203e718e-b61a-4876-a4c2-5eeb8d4f1011
            handle: null
            includeInCards: true
            instructions: null
            label: Subhead
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b4d08ce1-08d3-4fa0-a22b-283bdcac89a5
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-26T12:47:10+00:00'
            elementCondition: null
            fieldUid: 1654a904-945e-4b95-9c82-89ac1891012e
            handle: null
            includeInCards: false
            instructions: null
            label: Images
            providesThumbs: true
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8dac84dd-1cc8-4d17-9c8d-7bee050fc29f
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-26T12:47:10+00:00'
            elementCondition: null
            fieldUid: 8451e69a-89a7-4204-94e9-d6a5b929356f
            handle: backgroundColor
            includeInCards: false
            instructions: null
            label: 'Background Color'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5f4ad01c-eb0f-4264-983c-74f7124b7206
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 1bb40081-63b9-4e3d-b1f1-df4e91c0f1d4
        userCondition: null
handle: carousel
hasTitleField: false
icon: null
name: Carousel
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
