fieldLayouts:
  c287b1b5-fbb8-49a2-9cb1-4981029d78db:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: Title
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 0ae94cd1-0ff8-4630-915d-353d5c4eabfe
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9afe3d99-95db-4f7d-977b-d12ff3c82fa9 # Body
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5caa30cb-a9d9-492a-974a-adb54984f8df
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 771ba179-2c59-4389-bad3-882ce829a509 # Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fd33063d-ec61-47a5-9cb9-47d4835184a8
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6d8c2249-7976-4ec4-9ebe-db7e553e73fd # Show Date & Author
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7819c9b6-6a9c-4307-8a22-032e117ab477
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0ae9699f-02b3-4ff0-bd73-ea5c2c0476e4 # Subheading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9b3078ca-38be-4d61-b386-90f9859bfc51
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: bcaf43d6-0a78-4d23-983d-b0c2cc60d59c # Thumbnail
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a1dd284d-b916-4c51-8226-7ec26ac65ab3
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: bad14d4c-7164-4321-8f0f-933b1dcd723f # Case Study Category
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ab6e94ef-d21f-4ef5-a72e-da8998748f23
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 14b10afb-9c39-4ca4-a740-c4bbbd04f101 # Page Builder
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1f99464a-998a-4957-88cd-fa7996bcf48d
            userCondition: null
            warning: null
            width: 100
        name: Capabilities
        uid: 1d04a8f7-6077-4bf8-8e86-c96a1ae5420d
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 2d042d9b-af16-4d98-9347-8aadaad910b4 # Page Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e4e9cb9f-c0e4-4f83-9a00-eebf0541be02
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 784189f8-141b-4901-a137-08ab2d5b1a56 # Meta Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2dcefd36-7d1d-48ec-ac01-287d0628941f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2de2c9bb-2614-4aee-92ad-8acc2273975d # Canonical URL
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4d67ba68-f5a5-49a5-b1ee-b34cd406d452
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: dda2aa22-ce74-41a0-b919-85a4bc5563a7 # Robots Noindex, Nofollow
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d78d78a7-5921-471f-81e8-a03400ed5aef
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: 25390458-918a-48a5-8926-33e001ca7917
        userCondition: null
handle: caseStudies
hasTitleField: true
name: 'Case Studies'
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: ''
