fieldLayouts:
  42b7839c-0a2e-493a-b04e-4f7657ba30be:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: Title
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 0b382f0b-4ac5-4470-be07-4426a1f0724c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: acd917a2-35ae-4502-a64f-dc36848d8818 # Hero Subhead
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ffe0b98a-fb15-447b-bd52-035cebf4be7d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 88818712-b173-4d80-ba5a-16afc073ce89 # Hero Button
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 910fdbeb-b21b-4445-b52a-6eafca8fb4bf
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d477efc8-16f2-4f50-8b28-25c9792ba7b5 # Hero Background Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: beaee720-ed05-4d05-a282-03663aa0630d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 88eb9254-0c5f-414f-b165-148f2ad8d401 # Overview
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0c04098d-db5c-46eb-b16a-fb85e4885adf
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 14b10afb-9c39-4ca4-a740-c4bbbd04f101 # Page Builder
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a208ba40-8d75-417b-95b4-90d085a68d9d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 292c0922-e124-44f3-812d-dbd947ea0672 # Links
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 208d970d-dcdf-463d-bfa7-95ea9a0e1f67
            userCondition: null
            warning: null
            width: 100
        name: Common
        uid: a2c5e376-03bb-4716-89aa-1f9bfb0340aa
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 2d042d9b-af16-4d98-9347-8aadaad910b4 # Page Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 943b1035-b30a-4830-bc61-4293d29baf20
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 784189f8-141b-4901-a137-08ab2d5b1a56 # Meta Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 253731ea-834a-42cd-8ab8-1a9d6afed6fa
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2de2c9bb-2614-4aee-92ad-8acc2273975d # Canonical URL
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 94af4f46-ce18-49df-a4b5-739dfd59c7b0
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: dda2aa22-ce74-41a0-b919-85a4bc5563a7 # Robots Noindex, Nofollow
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: adeb9843-63f4-4c93-a731-69e6f8021a31
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: 9c8e87cf-eb60-4d9c-9abc-f5f01f569cb7
        userCondition: null
handle: company
hasTitleField: true
name: Company
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: ''
