fieldLayouts:
  54a14ce3-6db7-40b3-a232-addbcaa0bb0b:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 5b7efb7f-c142-4f7a-966c-f55f5c7f8238
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 88eb9254-0c5f-414f-b165-148f2ad8d401 # Overview
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 77364c68-7524-4482-ab30-fe3aae10009b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e2aecefd-a072-469f-92e4-3e62f3c498d7 # Callout Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 47df23c1-28fa-4170-92be-a1583121872c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: dea45362-35c2-43a9-a972-bb5505578a2b # Callout Body
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ddddfb74-949f-43b1-ac0c-3ca2e207e008
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: de1af0ae-1cff-4891-8176-093ad8bc2331 # Contact Info
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 595aca3a-56ec-4311-86fa-1cdbb80ff1ae
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 775f0af5-8bb7-44a5-9c99-dbfd56b8415f # Form
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6a1b37be-4541-414b-8f8f-46244d46c130
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: cce95aed-330d-428a-b48a-e6c646bb6494 # Form Iframe
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c69632c5-3101-4246-af3c-0cb26dac22fc
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 292c0922-e124-44f3-812d-dbd947ea0672 # Links
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 52c14745-a3ae-41a2-a1c4-cff5e2d8abf7
            userCondition: null
            warning: null
            width: 100
        name: Contact
        uid: 49819996-84c6-4211-a2ec-3c909d4cba94
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 2d042d9b-af16-4d98-9347-8aadaad910b4 # Page Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b0ccb44f-0038-43ac-b9b8-fb3cc188e9ed
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 784189f8-141b-4901-a137-08ab2d5b1a56 # Meta Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: da64f32b-a5a9-46e2-b880-40bfabdd2071
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2de2c9bb-2614-4aee-92ad-8acc2273975d # Canonical URL
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a45a5d7a-e3f1-4197-94cc-0cefc6e36232
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: dda2aa22-ce74-41a0-b919-85a4bc5563a7 # Robots Noindex, Nofollow
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 86854911-9279-46a9-afe4-271dfe53992b
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: 9c580dce-9e5a-498f-a546-97bfade62f74
        userCondition: null
handle: contact
hasTitleField: false
name: Contact
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: none
