color: null
fieldLayouts:
  e162d31f-ff73-438b-9d0f-c6d2f87f1a87:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-02-26T12:47:10+00:00'
            elementCondition: null
            fieldUid: cdb17897-96c7-4ca7-8794-14de165b137d
            handle: null
            includeInCards: true
            instructions: null
            label: 'Day Description'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6c90b59e-9a15-4ff8-9659-aefd41cb0aba
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-26T12:47:10+00:00'
            elementCondition: null
            fieldUid: a7b5e677-49d5-40db-98a4-b0064745267f
            handle: null
            includeInCards: false
            instructions: null
            label: 'Start Time'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6b4c2742-682b-4c0c-9739-2b02a654682f
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-26T12:47:10+00:00'
            elementCondition: null
            fieldUid: 8f91f027-420c-4ad2-bccd-c1c973944fcf
            handle: null
            includeInCards: false
            instructions: null
            label: 'End Time'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 411efc9a-d6e7-427f-8c02-91131a64200c
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 0b64ae01-89bc-4077-9f8e-39fe85deac87
        userCondition: null
handle: day
hasTitleField: false
icon: null
name: Day
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
