color: green
fieldLayouts:
  7f63b065-be87-4e5a-aa81-b80dd20b49db:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-03-28T20:44:48+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: b05c9fee-a1db-41c6-9485-36dce508ceb0
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-03-28T20:46:38+00:00'
            elementCondition: null
            fieldUid: 9889ed47-5d0f-4810-b306-638137c1baf4 # Form
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 80e513a7-3276-4b9d-9c9c-885b45b78a3a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: c4d1ce3d-8636-44cc-947b-3d3929839a4c
        userCondition: null
handle: formBlock
hasTitleField: true
icon: input-text
name: Form
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: 'Form Block'
titleTranslationKeyFormat: null
titleTranslationMethod: site
