color: green
fieldLayouts:
  7f63b065-be87-4e5a-aa81-b80dd20b49db:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-05-27T21:40:29+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 5a0b3d75-fc6f-4790-a058-64fb63c26c61 # Heading
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cc2e926c-2f9b-4105-936f-156f871ef5fb
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-03-28T20:46:38+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 9889ed47-5d0f-4810-b306-638137c1baf4 # Form
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 80e513a7-3276-4b9d-9c9c-885b45b78a3a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: c4d1ce3d-8636-44cc-947b-3d3929839a4c
        userCondition: null
handle: formBlock
hasTitleField: false
icon: input-text
name: Form
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: 'Form Block: {heading}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
