fieldLayouts:
  f4b51710-3d63-44eb-b74e-bb50f0d7ea35:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: Title
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 6131db7f-cdcd-4085-9d38-73a7cfb5924a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: acd917a2-35ae-4502-a64f-dc36848d8818 # Hero Subhead
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 05a3ce06-4dda-4d70-84b3-8a90611196d7
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 88818712-b173-4d80-ba5a-16afc073ce89 # Hero Button
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f3bba367-402c-4a7f-829a-bdf622a643fd
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d477efc8-16f2-4f50-8b28-25c9792ba7b5 # Hero Background Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f76dcf9b-8a01-4b7f-a538-c60b96d7f5bc
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 88eb9254-0c5f-414f-b165-148f2ad8d401 # Overview
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0f62e75f-3c2b-4251-bbd6-a5fcf6a8f8ce
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 14b10afb-9c39-4ca4-a740-c4bbbd04f101 # Page Builder
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 89ec1223-ae0f-4d97-a2f0-d129d5ef7d32
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 292c0922-e124-44f3-812d-dbd947ea0672 # Links
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ff18fb39-cf6f-43e6-a62c-8488fd436ffc
            userCondition: null
            warning: null
            width: 100
        name: Common
        uid: 5b277e7f-a3a5-4752-b492-4c1f93d2e14c
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 2d042d9b-af16-4d98-9347-8aadaad910b4 # Page Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7cdb1c16-0a72-4d92-a2d5-3a5ee983890d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 784189f8-141b-4901-a137-08ab2d5b1a56 # Meta Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ad09a57f-8aa0-444b-9c46-72809a04d74c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2de2c9bb-2614-4aee-92ad-8acc2273975d # Canonical URL
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 36b5f28f-9c40-4988-8d79-6c57623959e7
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: dda2aa22-ce74-41a0-b919-85a4bc5563a7 # Robots Noindex, Nofollow
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0d819699-7b2d-466f-b176-c20e6e5f812d
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: 7aeed62d-c9ef-4e2b-9ad2-7fd9a8d6b057
        userCondition: null
handle: generalPage
hasTitleField: true
name: 'General Page'
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: ''
