color: null
fieldLayouts:
  e845b843-3b11-41d6-ab3e-196eb4a841c5:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-03-27T22:12:47+00:00'
            elementCondition: null
            fieldUid: d7fde577-07c5-4dcf-8d55-83ab9d8f846c # Eyebrow
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e5b083f0-8cb0-4d06-9f52-c644500fa585
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-03-27T22:12:47+00:00'
            elementCondition: null
            fieldUid: 5a0b3d75-fc6f-4790-a058-64fb63c26c61 # Heading
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0d81b342-cf42-4207-85dc-6df797e7fcb4
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-03-27T22:12:47+00:00'
            elementCondition: null
            fieldUid: bf0d099c-51f4-498c-8c1f-7207be1ba990 # Simple Content
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f3b9cf31-6120-4723-8e7c-41a744621fb3
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-03-27T22:12:47+00:00'
            elementCondition: null
            fieldUid: 3ef69843-ea50-4c2c-888d-d10430a11f58 # Links
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e90dd56d-e852-4b5c-9bc3-485e980e723b
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: c0e1db2d-6373-46a7-b096-1f7823128101
        userCondition: null
handle: heroDefault
hasTitleField: false
icon: mask
name: 'Hero Default'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
