color: green
fieldLayouts:
  e845b843-3b11-41d6-ab3e-196eb4a841c5:
    cardView:
      - 'layoutElement:0d81b342-cf42-4207-85dc-6df797e7fcb4'
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-05-27T21:41:48+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 8287ff8e-bc32-4768-bc9b-e2d245408dfc # Short Text
            handle: eyebrow
            includeInCards: false
            instructions: null
            label: Eyebrow
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cf6fd242-c4f7-41fc-968e-6eae4d0f90b4
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-03-27T22:12:47+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 5a0b3d75-fc6f-4790-a058-64fb63c26c61 # Heading
            handle: null
            includeInCards: true
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0d81b342-cf42-4207-85dc-6df797e7fcb4
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-03-27T22:12:47+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: bf0d099c-51f4-498c-8c1f-7207be1ba990 # Simple Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f3b9cf31-6120-4723-8e7c-41a744621fb3
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-03-27T22:12:47+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 3ef69843-ea50-4c2c-888d-d10430a11f58 # Actions
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e90dd56d-e852-4b5c-9bc3-485e980e723b
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: c0e1db2d-6373-46a7-b096-1f7823128101
        userCondition: null
handle: heroDefault
hasTitleField: false
icon: mask
name: 'Hero - Default'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: 'Hero Default: {heading}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
