color: orange
fieldLayouts:
  890e237a-0b60-4225-8e63-613ccafaaa70:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-03-27T21:06:48+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 1bad44e5-b632-4651-a966-5b3bdc3a7608
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-27T21:36:12+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 6d911a2a-162d-4f6f-ade3-7e274512eb58 # Hero
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3d1d6baa-c868-413f-a7e4-b316479305b8
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-27T21:36:12+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 0f2d45b7-4084-422c-9ded-16040dc5a65c # Page Builder
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b4d976a2-e09b-41ca-ac51-5de71e80da89
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 02a26137-5fce-4e91-809e-f64f0d076cce
        userCondition: null
handle: homepage
hasTitleField: true
icon: file
name: 'Page - Home'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
