color: null
fieldLayouts:
  890e237a-0b60-4225-8e63-613ccafaaa70:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-03-27T21:06:48+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 1bad44e5-b632-4651-a966-5b3bdc3a7608
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-03-27T21:44:24+00:00'
            elementCondition: null
            fieldUid: 32bcee44-6bd1-40fc-b7ec-d119b5c317b3 # Home Builder
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8556a760-187f-4fcd-b752-e6c1069563f8
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 02a26137-5fce-4e91-809e-f64f0d076cce
        userCondition: null
handle: homepage
hasTitleField: true
icon: file
name: Homepage
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
