fieldLayouts:
  299a9240-e733-4797-b528-ee918e89485f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: Title
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: b8ef373f-0178-47d3-a242-48f5540729dd
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 771ba179-2c59-4389-bad3-882ce829a509 # Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5c842a8f-f828-4940-bef8-eff23ded9287
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0ae9699f-02b3-4ff0-bd73-ea5c2c0476e4 # Subheading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0bb0259f-cb06-4236-8431-f958230e8a53
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6d8c2249-7976-4ec4-9ebe-db7e553e73fd # Show Date & Author
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 83268d52-2a4c-4485-9cec-3cceeef82a97
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: bcaf43d6-0a78-4d23-983d-b0c2cc60d59c # Thumbnail
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 988944eb-c3e7-4a9e-978e-8ccdd77d2ccf
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9afe3d99-95db-4f7d-977b-d12ff3c82fa9 # Body
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3d468112-2b68-4d6e-aec6-58677cc7b484
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9da24b2d-1220-47b4-a6de-168f931500c6 # Industry Category
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 20b80008-9cec-411e-a198-1c8b89e88c5a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 14b10afb-9c39-4ca4-a740-c4bbbd04f101 # Page Builder
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3080725f-dd14-4148-859d-0cf14d8994c0
            userCondition: null
            warning: null
            width: 100
        name: Industries
        uid: f6f775bd-c97b-4250-9a80-673dc0033f5e
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 2d042d9b-af16-4d98-9347-8aadaad910b4 # Page Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2f56ecbd-80c4-482d-8cd8-3bc528da8621
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 784189f8-141b-4901-a137-08ab2d5b1a56 # Meta Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 793eaba8-dc16-417c-a999-050a9747c775
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2de2c9bb-2614-4aee-92ad-8acc2273975d # Canonical URL
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4349eb8c-1e9c-4eff-a410-23b240564d23
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: dda2aa22-ce74-41a0-b919-85a4bc5563a7 # Robots Noindex, Nofollow
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ccc610cf-c0db-42e3-a2d6-7a15c9101444
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: 6ef7ce1b-4eb0-4230-8b52-7ff577d740f3
        userCondition: null
handle: industries
hasTitleField: true
name: Industries
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: ''
