color: null
fieldLayouts:
  afe5d407-f09b-4188-bc23-47e95615db9a:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-02-26T12:47:10+00:00'
            elementCondition: null
            fieldUid: 6ddc949e-0b1c-4c10-a11c-8041972d3e1b
            handle: heading
            includeInCards: true
            instructions: null
            label: Heading
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5f90f1d3-bb8a-4074-9a28-06c194dc1311
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-26T12:47:10+00:00'
            elementCondition: null
            fieldUid: 26f3399b-67b2-469d-9cab-e7ec7780807a
            handle: null
            includeInCards: false
            instructions: null
            label: Instructions
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 86abcdf4-8cb2-4c29-85e9-94fb72e9e456
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-26T12:47:10+00:00'
            elementCondition: null
            fieldUid: 4288c084-b72d-43ff-81ff-65daac6b8474
            handle: backgroundColor
            includeInCards: false
            instructions: null
            label: 'Background Color'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ba2ef8aa-a158-463c-9d9a-f930c6eecc2d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-26T12:47:10+00:00'
            elementCondition: null
            fieldUid: 63bf3fd0-21ba-43e2-958b-22dda6ed50fb
            handle: null
            includeInCards: false
            instructions: null
            label: 'Button Color'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f37d238f-96b2-4c6f-addc-44bb28252ce1
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-26T12:47:10+00:00'
            elementCondition: null
            fieldUid: 9d10424b-b109-41e7-b202-e2480a193736
            handle: null
            includeInCards: false
            instructions: null
            label: Links
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b1165ac3-7d27-4ce1-8256-2e2a1ad4c35f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 1cb62ded-c695-44ec-8538-25f643c13ba4
        userCondition: null
handle: options
hasTitleField: false
icon: null
name: Options
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
