fieldLayouts:
  132dfba1-2343-4f79-9631-37855e902868:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 54fe7c89-1acc-43d7-826e-566030fc59b4
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d477efc8-16f2-4f50-8b28-25c9792ba7b5 # Hero Background Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 21743adc-9176-4d9e-a35e-bbc2f51fc3d0
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: acd917a2-35ae-4502-a64f-dc36848d8818 # Hero Subhead
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d14bc737-1766-49b1-a9e5-73454f186eae
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 88818712-b173-4d80-ba5a-16afc073ce89 # Hero Button
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 18b64035-f2e9-4438-b7cb-92e3050f3b46
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 88eb9254-0c5f-414f-b165-148f2ad8d401 # Overview
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 70142b6b-31be-4136-a19b-75e846519bd6
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 57f191b1-3da5-41d9-850a-8301da17d9ae # Callout Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: adb71518-05e3-4e64-9b46-f005edd46194
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d5fe9b3e-056a-48d2-9ba4-af57e686c520 # Callout Body
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1b060bda-6afc-452c-bd96-bcb5d111566f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ac3d9758-06cb-483e-8aed-c79fcbfc3a71 # Contact Info
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 04196299-eaae-467e-bebf-e31c181435be
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f9dc739c-50c3-4ecb-83e1-dc09d612f4c1 # Form
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7c5c5977-b095-4258-93c9-dea887e43026
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 292c0922-e124-44f3-812d-dbd947ea0672 # Links
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 05673362-951e-47b3-b999-4a6fbbe29485
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7c40f0d7-d17c-4363-86e2-96e74816806a # Multi-column List Section
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fc0969df-7de8-40dc-aa81-f8f03bdfc789
            userCondition: null
            warning: null
            width: 100
        name: 'Parts & Service'
        uid: dc8e37a5-78f0-4709-bcc4-29b944f4fa1e
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 2d042d9b-af16-4d98-9347-8aadaad910b4 # Page Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2bc039cc-6539-4894-ab0c-e98126af5c23
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 784189f8-141b-4901-a137-08ab2d5b1a56 # Meta Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ba009d38-08c4-403a-bcaa-de9ef0007ef8
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2de2c9bb-2614-4aee-92ad-8acc2273975d # Canonical URL
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 74d8b987-f4b6-4472-82b2-a881421248c0
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: dda2aa22-ce74-41a0-b919-85a4bc5563a7 # Robots Noindex, Nofollow
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b8437233-4029-4ce8-acbf-159c71539c38
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: 5f95a52f-2f65-4381-953c-d40f3f05c2f6
        userCondition: null
handle: partsAndService
hasTitleField: true
name: 'Parts & Service'
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
