fieldLayouts:
  b5261148-579e-4388-95f5-5ab625807fe5:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: Title
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 98c09267-eba8-498d-a6bc-82e89d9b2875
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: acd917a2-35ae-4502-a64f-dc36848d8818 # Hero Subhead
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0b3e1586-1f38-409c-bf3b-a5b5230ad10e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 88818712-b173-4d80-ba5a-16afc073ce89 # Hero Button
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 93475ae9-0eff-4cd3-b39b-f32830e5817a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d477efc8-16f2-4f50-8b28-25c9792ba7b5 # Hero Background Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 55c9225e-2885-42e8-ad66-1c04a39c7d9b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 88eb9254-0c5f-414f-b165-148f2ad8d401 # Overview
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d02d11cc-9f6c-4e9f-be6a-ce262ece9c00
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 14b10afb-9c39-4ca4-a740-c4bbbd04f101 # Page Builder
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1f7c3763-1571-448e-94d7-c8612af50fe9
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 292c0922-e124-44f3-812d-dbd947ea0672 # Links
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6ec3d02a-08ea-4d1c-9906-50d9c543f952
            userCondition: null
            warning: null
            width: 100
        name: Common
        uid: bc0dcca7-1219-4bc5-ab07-e37b9daeed10
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 2d042d9b-af16-4d98-9347-8aadaad910b4 # Page Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f30665b9-7ce9-4803-98cb-ae1222888fbb
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 784189f8-141b-4901-a137-08ab2d5b1a56 # Meta Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8a5b0921-869d-497b-a15b-787249aaa2e5
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2de2c9bb-2614-4aee-92ad-8acc2273975d # Canonical URL
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3e01a5a9-db1d-49e1-8aac-7cd561bd2a2f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: dda2aa22-ce74-41a0-b919-85a4bc5563a7 # Robots Noindex, Nofollow
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ed633350-f33f-4623-8652-23fc56067a3c
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: 338e8ef1-d10e-4e14-b6b3-15140e5a00d5
        userCondition: null
handle: partsAndServicePages
hasTitleField: true
name: 'Parts & Service Pages'
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
