fieldLayouts:
  bd5c68c5-07b7-4e85-86dd-4cdfc68b9c2a:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: Title
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 17056852-4365-4667-8405-d743f2713515
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ad75332d-8f1c-4f82-adb6-4e2ae9c671bd # Summary
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 50479e56-6a49-45bd-9d02-f5ffb2c4ab95
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b6c25cd5-7401-4210-8172-c44118005efe # Thumbnail
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c57064a2-dad8-4c48-abdb-2a176f58c0f4
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0b58a983-fb6b-4230-8c7a-4c25037e711a # Body
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ce14eb7f-5790-42a8-9e2c-e2f1168c697a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 87871504-0db0-4e36-9fe2-0f004afba14c # Attachments
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 441fd5e9-6a40-42b1-a982-d2b6272432b8
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a2da3692-a560-4759-8196-f3f7ebd3d6ae # Press Clipping URL
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2c9b38cf-740a-40bc-9587-dae078e9f503
            userCondition: null
            warning: null
            width: 100
        name: 'Press Releases'
        uid: 70eb6a34-b185-45b4-8bcd-a25781e0f47f
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 2d042d9b-af16-4d98-9347-8aadaad910b4 # Page Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b5f50fc9-62c3-4858-90d7-3d696a6397ef
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 784189f8-141b-4901-a137-08ab2d5b1a56 # Meta Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8353bfaf-4c0b-43f5-9a70-d7df2c999dda
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2de2c9bb-2614-4aee-92ad-8acc2273975d # Canonical URL
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cd7a64a3-b091-4e5d-bb87-8c4727f213e6
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: dda2aa22-ce74-41a0-b919-85a4bc5563a7 # Robots Noindex, Nofollow
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c796985b-49c9-4590-aa71-03f4a12818b6
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 89c5f6f6-851b-4949-9794-207dc8c3849f # Unique ID
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 50728c0c-6572-4c60-b3be-2e4612828855
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: e26909c1-81ae-469b-880e-0bcd1cfd89d8
        userCondition: null
handle: pressRelease
hasTitleField: true
name: 'Press Release'
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: ''
