fieldLayouts:
  e4859d58-af7d-46b5-a1a0-a501c78a56c6:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 2f0951c9-5d89-4274-bf71-c9be0f60679e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c909ec5f-bc7b-47ac-9afb-93c47c5e8b24 # Product Thumbnail 
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bafc3446-081a-41fc-a501-69b93e706355
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e90e011d-3f9b-4da3-9d1b-84cc9f632ff3 # New Product
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 35b00f14-b15c-4513-93f3-1966fe2f143e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: edaecaf0-8696-47bd-aeed-7546496b6623 # Short Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: db7b0d55-9097-45f1-a299-32d8ecb04611
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 02a1098c-cf54-417b-a8c8-c5268393abfe # Categories
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d0957729-ff90-43a0-aec8-8da4d9265e21
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: acd917a2-35ae-4502-a64f-dc36848d8818 # Hero Subhead
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 52d6e5c8-3511-4ae6-9dcb-70ebe73c7fd2
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 88818712-b173-4d80-ba5a-16afc073ce89 # Hero Button
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c388ad04-7617-4a94-aaae-4371e818c8a9
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d477efc8-16f2-4f50-8b28-25c9792ba7b5 # Hero Background Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 98768539-da4f-4280-aa8e-63a735490dee
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 88eb9254-0c5f-414f-b165-148f2ad8d401 # Overview
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5ce44f27-30fc-4269-91a0-bedc40016456
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 14b10afb-9c39-4ca4-a740-c4bbbd04f101 # Page Builder
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 66e20b35-bb45-4695-bbd2-b268edb2eff9
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 292c0922-e124-44f3-812d-dbd947ea0672 # Links
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 32995dc3-a6b4-415d-827e-78a28971fdb3
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f386410d-8d88-4637-9446-9366ccbaa844 # Disable Additional Products 
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6b49e88c-740e-4260-8056-85515c4e6946
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: a585e7fd-cd5e-4d01-bcf7-4ffc2a93b630
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 2d042d9b-af16-4d98-9347-8aadaad910b4 # Page Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6b75d10d-bf5c-48d3-a8b7-e9d6b2c5f786
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 784189f8-141b-4901-a137-08ab2d5b1a56 # Meta Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c1b0004a-cb46-483c-bbc1-eb8f70102a20
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2de2c9bb-2614-4aee-92ad-8acc2273975d # Canonical URL
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 21c912b8-f396-4dc3-957a-f7c81c51d3c6
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: dda2aa22-ce74-41a0-b919-85a4bc5563a7 # Robots Noindex, Nofollow
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8b0d1dfc-ea07-42e7-96c4-679d006e0311
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: c3fa2e4e-b562-4d33-a846-41ada9a2d824
        userCondition: null
handle: productAlt
hasTitleField: true
name: 'Product - Alternative'
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 2
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
