fieldLayouts:
  209b3cb2-fb6a-4e0c-9222-d3d785ae343f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: Title
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 485eb837-8eb3-48ab-845a-a72d259feb70
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e90e011d-3f9b-4da3-9d1b-84cc9f632ff3 # New Product
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0d48d617-a985-4b9b-a5ec-679ebf614a8b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: edaecaf0-8696-47bd-aeed-7546496b6623 # Short Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f8b4882f-888c-47e8-9ff3-efec4242b823
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 02a1098c-cf54-417b-a8c8-c5268393abfe # Categories
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8f18a6c2-01fc-472f-bf6e-04a025ea87a1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 990de78c-41f5-4317-9302-05f7b159c19d # Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8fec1671-542b-48a9-a4d7-a3ef0732f4db
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 1e4eb109-0857-4226-a41b-8d831f36b081 # Images
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 028cfe86-8168-406d-b6a0-3895dfd55625
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a1f7d7c8-6550-44c8-9660-a3d33da75df6 # YouTube Videos
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0fd06c5b-c261-4e54-a42d-623f18a0956c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: cdb7ef5a-1af3-4952-83fa-1bf55956780c # 360ยบ Viewers
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: de56794a-79d3-46fa-9fb1-26ed4dfc7b28
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3f5409a5-7912-4293-893b-ae784a7ca840 # Product Gallery Sort Order
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a97d7f44-dbd7-448d-8544-9515a4f3f809
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 31928910-fadc-4811-bd23-4de3dee85b7b # Subhead Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 42c60a62-0fa0-4941-accf-b3dd53485c92
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d642ab83-7364-4bb9-af99-b146698e39bb # Subhead List
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b0ad79db-9b98-4c8c-bd78-76a96e3e8de1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: fa4d7a11-8448-448d-b0f2-7ac7873db15f # Tabs
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e4ee38cc-dc8b-4fea-919f-a03d4c9598e6
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 68d5c916-fba5-404a-beab-419b83a3a5b9 # Form
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5b533e0f-fd57-4291-88fe-c4d923c44c6e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: cce95aed-330d-428a-b48a-e6c646bb6494 # Form Iframe
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4bc793b5-3f1b-4c03-97b4-b6b9b550624d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f386410d-8d88-4637-9446-9366ccbaa844 # Disable Additional Products 
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 60fee4e7-0dbd-40e8-84e1-428b600f53ad
            userCondition: null
            warning: null
            width: 100
        name: Products
        uid: 63a082d4-2386-470b-bcbd-b88e0cf4d5e7
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 2d042d9b-af16-4d98-9347-8aadaad910b4 # Page Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d8eaa6a0-cba9-4b17-b6d2-7a9a36c9f783
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 784189f8-141b-4901-a137-08ab2d5b1a56 # Meta Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0433214c-2134-41bd-be6e-ab7fabc209c5
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2de2c9bb-2614-4aee-92ad-8acc2273975d # Canonical URL
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0b83d3c1-9932-40af-8980-3e215eaaaf65
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: dda2aa22-ce74-41a0-b919-85a4bc5563a7 # Robots Noindex, Nofollow
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f15c356e-58c6-4293-ac1f-93c93b85b51f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 89c5f6f6-851b-4949-9794-207dc8c3849f # Unique ID
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6acc4725-211b-4b8b-b727-4203ec0d7baa
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: 4bf2a9ca-a40b-4a64-8b0a-c4a06652f589
        userCondition: null
handle: product
hasTitleField: true
name: Product
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
