fieldLayouts:
  824d9723-4cf4-469e-8f68-936a7c2d9c64:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: bb595916-cccb-4ff4-b0b5-03c7a1342276
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 5d284d32-0181-416e-961f-8ef825412d90
        userCondition: null
handle: salespersonCountries
hasTitleField: true
name: 'Salesperson Countries'
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
