color: null
fieldLayouts:
  7541e73e-7c01-42ad-89b4-f6c6aff3f857:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-02-26T12:47:10+00:00'
            elementCondition: null
            fieldUid: b7241743-dbe4-4355-86db-b534d5690939
            handle: heading
            includeInCards: true
            instructions: null
            label: Heading
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dd31fff7-ee96-466d-8b18-d2f362629e48
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-26T12:47:10+00:00'
            elementCondition: null
            fieldUid: 4708ae97-ecf0-4938-9a91-2c65647f99f2
            handle: body
            includeInCards: false
            instructions: null
            label: Body
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 54fd853c-a183-4a53-b07d-3ddd6f6327b4
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-26T12:47:10+00:00'
            elementCondition: null
            fieldUid: 9ce74417-2c6e-469e-a15f-d6f7ec7d69ce
            handle: backgroundColor
            includeInCards: false
            instructions: null
            label: 'Background Color'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a69d0072-284d-442c-a234-24e694720017
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 86f0e566-bba6-4889-a64f-35c024c78faf
        userCondition: null
handle: sectionWithText
hasTitleField: false
icon: null
name: 'Section with Text'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
