color: null
fieldLayouts:
  ab63c901-2fa3-4754-99f0-8f57554a31f7:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-02-26T12:47:10+00:00'
            elementCondition: null
            fieldUid: e21a0aff-0e4a-4a34-835d-4464143d3976
            handle: image
            includeInCards: false
            instructions: null
            label: Image
            providesThumbs: true
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2042b665-16b8-4f14-b182-d95dafab9027
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-26T12:47:10+00:00'
            elementCondition: null
            fieldUid: 2fe883ca-66b9-4842-a18c-4bbfc83e17b7
            handle: null
            includeInCards: true
            instructions: null
            label: Caption
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6f063455-f3bf-4c5d-9e5a-5bb9c67fcc84
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-26T12:47:10+00:00'
            elementCondition: null
            fieldUid: 2d7e9cfd-b775-4cbb-9919-e3b5918bec93
            handle: null
            includeInCards: false
            instructions: null
            label: 'Background Color'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b35abfee-4562-4db6-b45b-3ef3a1b85008
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: ff32dbdd-3ef6-44c4-bd19-cf3b5dc25fc3
        userCondition: null
handle: singleImage
hasTitleField: false
icon: null
name: 'Single Image'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
