color: null
fieldLayouts:
  7e7ee3ae-baae-400d-b3f9-72de92f38550:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-02-26T12:47:10+00:00'
            elementCondition: null
            fieldUid: 9df9726f-c3b0-4adb-889e-c3d820b119eb
            handle: null
            includeInCards: true
            instructions: null
            label: 'Tab Label'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 891b3190-0dfe-4d79-b39c-5ebfa6efdc9f
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-02-26T12:47:10+00:00'
            elementCondition: null
            fieldUid: 12ace062-060c-41ac-9794-f2c88ab76efc
            handle: null
            includeInCards: false
            instructions: null
            label: Item
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0acdf34e-1d8a-4e2b-b626-7f238dfa4d2b
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 26294f8b-ddb3-4ff8-ba83-3eef442721b2
        userCondition: null
handle: tabList
hasTitleField: false
icon: null
name: 'Tab - List'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
