color: green
fieldLayouts:
  8b5e36ca-5a67-49ba-a85f-b0453c2b1681:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-05-27T21:39:06+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 5a0b3d75-fc6f-4790-a058-64fb63c26c61 # Heading
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6f45a181-5a41-42f2-958b-c753ed990e1d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-27T21:39:06+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: bf0d099c-51f4-498c-8c1f-7207be1ba990 # Simple Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a73b8faa-d955-46dd-9aad-274b913b81dc
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-05-27T21:39:06+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: eba35f19-2460-442a-a6dd-3af7438f8681 # Action
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7ba519fa-fde7-4309-8145-ed4c5c51400f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 39967f3f-23ec-4544-af15-18e7a5a72abf
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-05-27T21:39:06+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: d04505b0-157c-4c28-8060-158123f299c9 # Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d8639bc0-1d83-488f-ad46-a33f2639f22b
            userCondition: null
            warning: null
            width: 100
        name: Media
        uid: 50181c47-11c8-4158-b982-36ee4f412180
        userCondition: null
handle: textImageBlock
hasTitleField: false
icon: text
name: 'Text + Image'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: 'Text + Image: {heading}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
