fieldLayouts:
  11af7cf4-869e-4609-93ce-eac14a74caa8:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: Title
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: c2e10ee7-cad7-4bec-999a-baa811521f81
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 87829378-0c2a-4880-ab50-4a4a58ac4e4f # YouTube Video
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c3141545-aafc-49cf-8f96-fe37a83c9fc0
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9590ae89-e2d7-46c6-b9d5-cd89b48c2def # Short Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 15488b58-cfdd-4ddd-a68a-39f6bd72bd82
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 24e9205c-1672-45fe-acc1-2c3a17a882da # Long Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 23c5c1d3-0eb4-4f54-adec-cd7d1e99135c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 090ea542-8108-4c65-accb-7422abf1bcea # Categories
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e7c320a3-bea0-4cc2-9942-bb45a04e7b88
            userCondition: null
            warning: null
            width: 100
        name: Videos
        uid: acf1870c-65f8-4912-b371-713315842b6c
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 2d042d9b-af16-4d98-9347-8aadaad910b4 # Page Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 05003223-85cb-408b-ae55-034367e44366
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 784189f8-141b-4901-a137-08ab2d5b1a56 # Meta Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2419a271-f951-444a-9478-af92f1ceaa8f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2de2c9bb-2614-4aee-92ad-8acc2273975d # Canonical URL
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5b20fbe0-cc92-4ad7-a82a-fca9e571155e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: dda2aa22-ce74-41a0-b919-85a4bc5563a7 # Robots Noindex, Nofollow
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 70768882-4738-4b80-a69f-5fc28a4d2e56
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: bdce8059-d3f3-49af-a359-27a4d71c330f
        userCondition: null
handle: videos
hasTitleField: true
name: Videos
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: none
