fieldLayouts:
  0bee0287-7aeb-4377-ad13-07a1213077af:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: c7f2f0c2-45a3-4793-8602-d5cb75eb1430 # Notification Bar
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 98e9b4f6-d071-4fac-8087-a15848ebdbb9
            userCondition: null
            warning: null
            width: 100
        name: 'Notification Bar'
        uid: 729e5731-18cb-48a6-b248-d3c415f3c05b
        userCondition: null
handle: notificationBar
name: 'Notification Bar'
sortOrder: 3
