defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 1cfb3efd-2b62-4198-a828-98f92217c469 # Blog
handle: blog
maxAuthors: 1
name: Blog
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  e0ba3b8c-6105-4307-b1a3-89fed57d7634:
    enabledByDefault: true
    hasUrls: true
    template: pages/_entry.twig
    uriFormat: 'blog/{slug}'
type: channel
