defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: b01b4132-c6e9-4b48-8ab5-e7ac735d0117 # Blog Index
handle: blogIndex
maxAuthors: 1
name: 'Blog Index'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  e0ba3b8c-6105-4307-b1a3-89fed57d7634:
    enabledByDefault: true
    hasUrls: true
    template: pages/_entry.twig
    uriFormat: blog
type: single
