defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 5b88e4da-8ccd-4aac-ac8f-33e3d7debd0a # Home
handle: home
name: Home
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  c0ea20be-803e-4be3-9775-fc071aa393e1: # G O L D E N
    enabledByDefault: true
    hasUrls: true
    template: singles/_home
    uriFormat: __home__
type: single
