defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: c2eecb67-e3c1-48ae-abd2-03cf16e1b03e # Homepage
handle: homepage
maxAuthors: 1
name: Homepage
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  e0ba3b8c-6105-4307-b1a3-89fed57d7634: # $PRIMARY_SITE_NAME
    enabledByDefault: true
    hasUrls: true
    template: index.twig
    uriFormat: __home__
type: single
