defaultPlacement: end
enableVersioning: false
entryTypes:
  -
    uid: 0bdb47e6-b96c-4c83-9042-dc0ea5f13882 # Parts & Service
handle: partsAndService
name: 'Parts & Service'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  c0ea20be-803e-4be3-9775-fc071aa393e1: # G O L D E N
    enabledByDefault: true
    hasUrls: true
    template: singles/_parts-and-service
    uriFormat: parts-and-service
type: single
