defaultPlacement: end
enableVersioning: false
entryTypes:
  -
    uid: 32a38d20-6d69-408d-8f5f-18b6dacc5b44 # Product
  -
    uid: de10643f-66dd-4120-bf5b-8647192d74d9 # Product - Alternative
handle: products
name: Products
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  c0ea20be-803e-4be3-9775-fc071aa393e1: # G O L D E N
    enabledByDefault: true
    hasUrls: true
    template: products/_entry
    uriFormat: 'products/{slug}'
structure:
  maxLevels: 1
  uid: e0241392-a057-47a3-8c62-154d084e0836
type: structure
