defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 74291831-78db-456c-872c-ab5cd41cbc48 # Product Brands
handle: productBrands
name: 'Product Brands'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  c0ea20be-803e-4be3-9775-fc071aa393e1: # G O L D E N
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: 'product-brands/{slug}'
type: channel
