defaultPlacement: end
enableVersioning: false
entryTypes:
  -
    uid: b7592cfd-db93-4b1d-af2b-991535d19a8e # Salesperson Canadian Provinces
handle: salespersonCanadianProvinces
name: 'Salesperson Canadian Provinces'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  c0ea20be-803e-4be3-9775-fc071aa393e1: # G O L D E N
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: channel
