defaultPlacement: end
enableVersioning: false
entryTypes:
  -
    uid: 34c52476-1f42-45cd-9b9d-59684d0d0f59 # Salesperson Countries
handle: salespersonCountries
name: 'Salesperson Countries'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  c0ea20be-803e-4be3-9775-fc071aa393e1: # G O L D E N
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: channel
