columnSuffix: null
contentColumnType: text
handle: blVertImgWhiteBlue
instructions: null
name: 'Vertical Image (White/Blue)'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: text
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: site
type: craft\fields\PlainText
