columnSuffix: null
handle: boothOffer
instructions: null
name: 'Booth - Brand Booth - Offer'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: false
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: site
type: craft\fields\PlainText
