columnSuffix: null
contentColumnType: string
handle: businessLine
instructions: null
name: 'Business Line'
searchable: true
settings:
  allowSelfRelations: false
  allowSubfolders: false
  allowUploads: true
  allowedKinds: null
  branchLimit: null
  defaultUploadLocationSource: 'volume:70a8ba0e-8bed-49ec-81cb-1ac3937ea5fd' # golden-files.pmassets.com
  defaultUploadLocationSubpath: null
  localizeRelations: true
  maintainHierarchy: false
  maxRelations: 1
  minRelations: null
  previewMode: full
  restrictFiles: false
  restrictLocation: false
  restrictedDefaultUploadSubpath: null
  restrictedLocationSource: 'volume:70a8ba0e-8bed-49ec-81cb-1ac3937ea5fd' # golden-files.pmassets.com
  restrictedLocationSubpath: null
  selectionLabel: null
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: true
  sources:
    - 'volume:70a8ba0e-8bed-49ec-81cb-1ac3937ea5fd' # golden-files.pmassets.com
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
