columnSuffix: null
contentColumnType: integer
handle: contactForm
instructions: 'Helper text'
name: Form
searchable: true
settings:
  forms: '*'
translationKeyFormat: null
translationMethod: site
type: Solspace\Freeform\FieldTypes\FormFieldType
