columnSuffix: null
handle: longContent
instructions: null
name: 'Long Content'
searchable: true
settings:
  availableTransforms: ''
  availableVolumes: ''
  characterLimit: null
  ckeConfig: 2296980a-ccb9-422a-995b-0f095004234a # Long Content
  createButtonLabel: null
  defaultTransform: null
  entryTypes:
    -
      __assoc__:
        -
          - uid
          - 252a470c-0dab-48be-869e-f6268290a3df # Image
    -
      __assoc__:
        -
          - uid
          - 5f52bec5-60be-4ae5-994e-b1e3454b0230 # Form
  expandEntryButtons: false
  fullGraphqlData: false
  parseEmbeds: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: true
  sourceEditingGroups:
    - __ADMINS__
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
