columnSuffix: null
handle: longContent
instructions: null
name: 'Long Content'
searchable: false
settings:
  availableTransforms: ''
  availableVolumes: ''
  ckeConfig: 2296980a-ccb9-422a-995b-0f095004234a # Long Content
  createButtonLabel: null
  defaultTransform: null
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  sourceEditingGroups:
    - __ADMINS__
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
