columnSuffix: null
contentColumnType: text
handle: mediaContact
instructions: null
name: 'Media Contact'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: text
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: site
type: craft\fields\PlainText
