columnSuffix: lzygdheo
handle: pbFormIframe
instructions: null
name: 'Page Builder - Section with Form - Form Iframe'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  initialRows: 3
  multiline: true
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
