columnSuffix: aqlxgxay
contentColumnType: boolean
handle: productsDisableAdditional
instructions: null
name: 'Disable Additional Products '
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
