columnSuffix: null
contentColumnType: boolean
handle: sdActionSellingCertified
instructions: null
name: 'Action Selling Certified?'
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Lightswitch
