columnSuffix: null
contentColumnType: text
handle: seoMetaDesc
instructions: null
name: 'Meta Description'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: text
  initialRows: 2
  multiline: true
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: site
type: craft\fields\PlainText
