columnSuffix: null
handle: shortContent
instructions: null
name: 'Short Content'
searchable: false
settings:
  availableTransforms: ''
  availableVolumes: '*'
  ckeConfig: dbe90f0d-a64e-40f9-9559-a2e0653bf4d8 # Short Content
  createButtonLabel: null
  defaultTransform: null
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  sourceEditingGroups:
    - __ADMINS__
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
