columnSuffix: null
handle: simpleContent
instructions: null
name: 'Simple Content'
searchable: false
settings:
  availableTransforms: ''
  availableVolumes: ''
  ckeConfig: ba72b5dd-9e9f-4b11-b3d3-2c5cb5bfa144 # Simple
  createButtonLabel: null
  defaultTransform: null
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  sourceEditingGroups:
    - __ADMINS__
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
