columnSuffix: null
contentColumnType: text
handle: threeSixtyRotatorUrl
instructions: null
name: 'Rotator URL'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: site
type: craft\fields\PlainText
