columnSuffix: null
contentColumnType: string
handle: threeSixtyViewers
instructions: null
name: '360ยบ Viewers'
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: null
  localizeRelations: true
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  selectionLabel: null
  showSiteMenu: true
  sources:
    - 'section:fc59be59-7113-4986-a086-73da128e1e2e' # 360ยบ Viewers
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
