defaultPlacement: end
fieldLayouts:
  620507cf-1508-44e8-a0c1-3219cd1aa519:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: 358c4cf9-cec0-43dd-b02b-d98714c635a2
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4fe5459e-932f-4ec8-8e1e-5bc5d98360d5 # Custom H1
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ef822802-a85c-4650-828b-4c78f3bce249
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 640c2f8f-7d40-43ac-9f74-ad11816ab2db # Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0646ad11-48ee-4d44-8134-66446a865a63
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d477efc8-16f2-4f50-8b28-25c9792ba7b5 # Hero Background Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 26e1d665-274b-4919-b907-344f4b694959
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9b6c6f32-7b00-4ad2-b160-3f8409c72ed0 # Thumbnail
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e7e8173a-c1b2-4dd0-8d86-d214f637916c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: fcd33cde-e84c-4c77-9500-d1d178e71389 # Body
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cda576d2-0c9c-4883-a316-916441a2bfa4
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2814d806-b1ef-471d-bd2d-9837f6251718 # Links
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 88e149cc-7aa8-474d-a1dc-fd35fe6f35b2
            userCondition: null
            warning: null
            width: 100
        name: Categories
        uid: a80f9f4b-ce5c-49f3-8ea1-6b8fafe5ec9b
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 2d042d9b-af16-4d98-9347-8aadaad910b4 # Page Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c252c7f3-23b6-4147-8749-bee1efeb02eb
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 784189f8-141b-4901-a137-08ab2d5b1a56 # Meta Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 28ffd6b2-144f-43a7-b894-c163dfa4c65a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2de2c9bb-2614-4aee-92ad-8acc2273975d # Canonical URL
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7af0d9ca-d47a-4da7-955c-7c27d54f5782
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: dda2aa22-ce74-41a0-b919-85a4bc5563a7 # Robots Noindex, Nofollow
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f96cfeb0-6635-49b8-b899-3edee774f1f9
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: 308e6822-e025-4168-8032-142d8c65ee6e
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: d326c25c-1ad1-48b1-bf3f-b5223b5e03f7 # Hide this language
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2c200811-aaa4-4706-8211-10d21b6b55b4
            userCondition: null
            warning: null
            width: 100
        name: Etc
        uid: 4f86eba0-3e30-4e55-a9b4-54c86b00a82b
        userCondition: null
handle: applicationCats
name: Applications
siteSettings:
  4fd61ef3-0957-4d1e-a593-dc93e645b835: # G O L D E N - Portuguese
    hasUrls: true
    template: capabilities/_category
    uriFormat: '{parent.uri}/{slug}'
  45d82af1-444b-4ef0-ae83-293ade46f8b3: # G O L D E N - Italian
    hasUrls: true
    template: capabilities/_category
    uriFormat: '{parent.uri}/{slug}'
  683aac47-3f36-4506-a033-58905fd2de87: # G O L D E N - German
    hasUrls: true
    template: capabilities/_category
    uriFormat: '{parent.uri}/{slug}'
  c0ea20be-803e-4be3-9775-fc071aa393e1: # G O L D E N
    hasUrls: true
    template: capabilities/_category
    uriFormat: '{parent.uri}/{slug}'
  e30f07eb-6153-416d-af2e-07c687e0a2f3: # G O L D E N - Spanish
    hasUrls: true
    template: capabilities/_category
    uriFormat: '{parent.uri}/{slug}'
  fc467f8d-ea71-4951-b9a2-a1cdd4163498: # G O L D E N - French
    hasUrls: true
    template: capabilities/_category
    uriFormat: '{parent.uri}/{slug}'
structure:
  maxLevels: null
  uid: 393b35fa-f94b-4bfa-b03a-f07f37054851
