defaultPlacement: end
fieldLayouts:
  f28e8202-1453-4cb5-9e56-b3ff6b13823f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: 198f3370-0a41-49f6-bdee-d59133d83a0e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4fe5459e-932f-4ec8-8e1e-5bc5d98360d5 # Custom H1
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cf3e79e9-e791-4cf0-9d69-af15ab768f1e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 640c2f8f-7d40-43ac-9f74-ad11816ab2db # Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 447c4b4c-722e-47b6-bcf2-dfcf5feff4bf
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d477efc8-16f2-4f50-8b28-25c9792ba7b5 # Hero Background Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b70d3f33-217e-49e0-8996-0706a3c3ed14
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9b6c6f32-7b00-4ad2-b160-3f8409c72ed0 # Thumbnail
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 633c6b8c-7529-4cb0-8e5d-5254114e2f64
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: fcd33cde-e84c-4c77-9500-d1d178e71389 # Body
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fdd5af23-c7e0-4c53-b72d-0c43598821f9
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2814d806-b1ef-471d-bd2d-9837f6251718 # Links
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1b5df886-04cf-42fa-b0c0-a9a7cd413c91
            userCondition: null
            warning: null
            width: 100
        name: Categories
        uid: fffc0a01-35f6-433a-a98a-9c05d1ff679f
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 2d042d9b-af16-4d98-9347-8aadaad910b4 # Page Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ac7f63dd-b3b6-4810-83de-eb63f482f8a1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 784189f8-141b-4901-a137-08ab2d5b1a56 # Meta Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c8d320d2-9f94-47a4-97ac-45db570ef580
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2de2c9bb-2614-4aee-92ad-8acc2273975d # Canonical URL
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 31789a05-b7da-4dfe-b161-37cec79d6391
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: dda2aa22-ce74-41a0-b919-85a4bc5563a7 # Robots Noindex, Nofollow
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a38b03cd-f20c-43a7-acd2-50e3561408c6
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: 5e576ffe-a7f0-4243-a54f-007a8a9fdb5d
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: d326c25c-1ad1-48b1-bf3f-b5223b5e03f7 # Hide this language
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 08c4a4b6-f310-4b01-a8fe-7582c4bbca76
            userCondition: null
            warning: null
            width: 100
        name: Etc
        uid: b579098c-37e7-4538-ba4b-8aa80e0b5512
        userCondition: null
handle: caseStudyCats
name: 'Case Studies'
siteSettings:
  4fd61ef3-0957-4d1e-a593-dc93e645b835: # G O L D E N - Portuguese
    hasUrls: true
    template: capabilities/_category
    uriFormat: '{parent.uri}/{slug}'
  45d82af1-444b-4ef0-ae83-293ade46f8b3: # G O L D E N - Italian
    hasUrls: true
    template: capabilities/_category
    uriFormat: '{parent.uri}/{slug}'
  683aac47-3f36-4506-a033-58905fd2de87: # G O L D E N - German
    hasUrls: true
    template: capabilities/_category
    uriFormat: '{parent.uri}/{slug}'
  c0ea20be-803e-4be3-9775-fc071aa393e1: # G O L D E N
    hasUrls: true
    template: capabilities/_category
    uriFormat: '{parent.uri}/{slug}'
  e30f07eb-6153-416d-af2e-07c687e0a2f3: # G O L D E N - Spanish
    hasUrls: true
    template: capabilities/_category
    uriFormat: '{parent.uri}/{slug}'
  fc467f8d-ea71-4951-b9a2-a1cdd4163498: # G O L D E N - French
    hasUrls: true
    template: capabilities/_category
    uriFormat: '{parent.uri}/{slug}'
structure:
  maxLevels: null
  uid: ce1c7757-96b4-4818-9c08-05c1d2b40d87
