defaultPlacement: end
fieldLayouts:
  a8243c6f-7c83-4ca3-ad67-12a9d358dffb:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: 46db4e03-4ca6-4722-9626-71b62d901e4f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4fe5459e-932f-4ec8-8e1e-5bc5d98360d5 # Custom H1
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 36d9441a-8602-45bc-a555-e7add177d126
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 640c2f8f-7d40-43ac-9f74-ad11816ab2db # Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2a0de956-9dff-4b1f-85fd-0cd01a31565d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d477efc8-16f2-4f50-8b28-25c9792ba7b5 # Hero Background Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c5f42368-2b8e-4fb3-9ef3-8c2e53855529
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9b6c6f32-7b00-4ad2-b160-3f8409c72ed0 # Thumbnail
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 86a0ae91-bb06-463e-b666-a3fa74316900
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: fcd33cde-e84c-4c77-9500-d1d178e71389 # Body
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ad195944-43ba-49d3-a184-10e0efa1278f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2814d806-b1ef-471d-bd2d-9837f6251718 # Links
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 070e9d28-32f3-4238-93f1-6af0e54f6ca7
            userCondition: null
            warning: null
            width: 100
        name: Categories
        uid: 90ab7cbf-eff4-4e32-b619-ddb74521d042
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 2d042d9b-af16-4d98-9347-8aadaad910b4 # Page Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fff16acf-d2d2-4fa0-aa05-b90013ea8a1b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 784189f8-141b-4901-a137-08ab2d5b1a56 # Meta Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 96ab9306-07e1-4ab9-9a5f-e9018bb7d7a8
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2de2c9bb-2614-4aee-92ad-8acc2273975d # Canonical URL
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 41f0156c-17cf-42df-a7ab-fd4648988537
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: dda2aa22-ce74-41a0-b919-85a4bc5563a7 # Robots Noindex, Nofollow
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 97fc58ed-30c1-45cd-8d40-9df098adea1e
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: cea76b76-1002-47bf-946c-ecb5536e9084
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: d326c25c-1ad1-48b1-bf3f-b5223b5e03f7 # Hide this language
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0ee06e21-e0bb-4c95-bbee-39064fa49c63
            userCondition: null
            warning: null
            width: 100
        name: Etc
        uid: d3527539-e11c-4bd2-8422-9efe8efe0799
        userCondition: null
handle: videoCats
name: Videos
siteSettings:
  4fd61ef3-0957-4d1e-a593-dc93e645b835: # G O L D E N - Portuguese
    hasUrls: true
    template: videos/_category
    uriFormat: '{parent.uri}/{slug}'
  45d82af1-444b-4ef0-ae83-293ade46f8b3: # G O L D E N - Italian
    hasUrls: true
    template: videos/_category
    uriFormat: '{parent.uri}/{slug}'
  683aac47-3f36-4506-a033-58905fd2de87: # G O L D E N - German
    hasUrls: true
    template: videos/_category
    uriFormat: '{parent.uri}/{slug}'
  c0ea20be-803e-4be3-9775-fc071aa393e1: # G O L D E N
    hasUrls: true
    template: videos/_category
    uriFormat: '{parent.uri}/{slug}'
  e30f07eb-6153-416d-af2e-07c687e0a2f3: # G O L D E N - Spanish
    hasUrls: true
    template: videos/_category
    uriFormat: '{parent.uri}/{slug}'
  fc467f8d-ea71-4951-b9a2-a1cdd4163498: # G O L D E N - French
    hasUrls: true
    template: videos/_category
    uriFormat: '{parent.uri}/{slug}'
structure:
  maxLevels: null
  uid: d648776f-0684-4402-9028-21207a523038
